name: Run readme-template create action

on:
  workflow_dispatch: # triggers manually
    inputs:
      template:
        description: 'Use the template of the readme: modulo, practica o proyecto '     
        required: true
        default: 'modulo'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2      
    - name: Clone templates folder
      uses: actions/checkout@v2
      with:
        repository: ULL-MII-SYTWS-2122/github-action-hello-world-carlos-diaz-calzadilla-alu0101102726
    - name: Run template action create
      uses: ULL-MII-SYTWS-2122/github-action-hello-world-carlos-diaz-calzadilla-alu0101102726@main 
      with:
         template: '${{ github.event.inputs.template }}'
  push:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Commit and push update
      run: |-
        git config --global user.email "trc@action.com"
        git config --global user.name "template-readme-Bot"
        git add README.md
        git commit -m "Added Readme from GitHub Actions"
        git push
